version: '3'

services:
  jenkins:
    container_name: jenkins
    image: inderpal2406/jenkins-ansible-docker
    build:
      context: jenkins_ansible_docker
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
  remote_host:
    container_name: remote_host
    image: inderpal2406/remote_host
    build:
      context: ./centos7/
    volumes: 
      - "$PWD/scripts/mysql_backup_to_aws.sh:/tmp/script.sh"
    networks:
      - net
  db_host:
    container_name: db_host
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=Corp@123"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
  web:
    container_name: web
    image: inderpal2406/ansible_web
    build:
      context: jenkins_ansible/web/
    ports:
      - "80:80"
    networks:
      - net

networks:
  net:
